Fix findParentNodeModules failing on paths with non-URI legal chars
docsbydoxdox/doxdox pull request #171
Opened 2022-04-16 16:45 UTC by kopischke

The `sanitizePath` function des not resolve percent encoded path characters, returning a path like `/my/path to/dir` as `/my/path%20to/dir`, which in turn makes `findParentNodeModules` fail on such paths.

The solution is to use Node’s [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl) instead. As that function’s signature is identical to `sanitizePath` and the only call site of the latter is inside `findParentNodeModules`, I’ve opted for removing `sanitizePath` entirely, but if you prefer the indirection, redefining it as an alias to `fileURLToPath` should be fine.

Apologies for the granular commits, but this was a quick hack in gitHub’s online commit interface.

2022-04-16 17:44 UTC, kopischke commented
Gah, I just noticed I also removed the JSDoc comments for `slugifiy` in 7c8ad5db5e1ffba389f4392c3deb273b2e9adcfe. Apologies, I’ll correct that ASAP.

2022-04-16 20:38 UTC, kopischke commented
Rebased to be two distinct commits: the fix for `findParentNodeModules` and the removal of `sanitizePath` (including its test). This should be ready for review.

2022-04-19 14:49 UTC, neogeek commented
Thank you for looking into this! Before merging I just want to check it out on both macOS and Windows (the main reason for original code). I'll try to do that tonight.

2022-04-22 16:39 UTC, neogeek requested changes

2022-04-22 16:39 UTC, neogeek commented on packages/doxdox-core/src/utils.test.ts
> +    parseIgnoreConfig
Everything looks good! I also updated the JSDoc parser to use the `fileURLToPath` method as it also used the `sanitizePath`. That fixed the tests on Windows for that plugin, so thank you again for submitting this PR!

The only issue I found was a missing comma after this import.

```suggestion
    parseIgnoreConfig,
```

2022-04-22 17:03 UTC, neogeek approved these changes

2022-04-22 17:04 UTC, merged